---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: {{ $.Values.acm_policy_set_name }}
  namespace: {{ $.Values.policy_set_namespace | default "default" }}
spec:
  description: "Set of ACM policies applied to all cluster(s) that is NOT labeled 'local-cluster'"
  policies:
  {{- range .Values.managed_clusters.acm_policies }}
    - {{.}}
  {{- end -}}
