---
splunk_servers:
  - name: splunk-1
    fqdn: 'http://splunk-server-1.example.com:8088'
    secret: vector-splunk-hec-token
    skip_tls_verify: true
    inputRefs:
#      - audit
      - application
      - infrastructure
  - name: splunk-2
    fqdn: 'https://splunk-server-2.example.com:8088'
    secret: vector-splunk-hec-token
    skip_tls_verify: false
    inputRefs:
      - audit
#      - application
#      - infrastructure

roles:
  - collect-audit-logs
  - collect-application-logs
  - collect-infrastructure-logs
