---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $.Values.acm_policy_name }}
  namespace: {{ $.Values.policy_namespace | default (printf "%+v-%+v" $.Values.cluster_name $.Values.default_namespace) }}
spec:
  dependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      kind: Policy
      name: aap-operator
      namespace: {{ $.Values.policy_namespace | default (printf "%+v-%+v" $.Values.cluster_name $.Values.default_namespace) }}
      compliance: Compliant
  disabled: false
  remediationAction: {{ $.Values.remediation_action | default "inform" }}
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-hub
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: automationhub.ansible.com/v1beta1
                kind: AutomationHub
                metadata:
                  name: {{ $.Values.name }}-hub
                  namespace: aap
                spec:
#                  sso_secret: automation-hub-sso # https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/deploying_the_red_hat_ansible_automation_platform_operator_on_openshift_container_platform/using-rhsso-operator-with-automation-hub#proc-creating-a-secret_using-a-rhsso-operator
                  pulp_settings:
                    CONNECTED_ANSIBLE_CONTROLLERS:
                      - >-
                        https://aap.{{ `{{ (lookup "config.openshift.io/v1" "Ingress" "" "cluster").spec.domain }}` }}
                    verify_ssl: false
#                    GALAXY_TOKEN_EXPIRATION: 10080 # 1 week in seconds
#                    TOKEN_AUTH_DISABLED: true
#                    GALAXY_VERIFY_KEYCLOAK_SSL_CERTS: true
#                    GALAXY_AUTHENTICATION_CLASSES:
#                      - rest_framework.authentication.SessionAuthentication
#                      - rest_framework.authentication.TokenAuthentication
#                      - galaxy_ng.app.auth.auth.RHIdentityAuthentication
#                      - galaxy_ng.app.auth.keycloak.KeycloakBasicAuth
                  hostname: {{ $.Values.name }}-hub
                  nginx_proxy_send_timeout: 120s
                  gunicorn_content_workers: 2
                  gunicorn_api_workers: 2
                  route_tls_termination_mechanism: Edge
                  ingress_type: Route
                  loadbalancer_port: 80
                  no_log: true
                  file_storage_size: 100Gi
                  image_pull_policy: IfNotPresent
                  nginx_proxy_read_timeout: 120s
                  gunicorn_timeout: 90
                  nginx_client_max_body_size: 10m
                  web:
                    replicas: 2
                  nginx_proxy_connect_timeout: 120s
                  haproxy_timeout: 180s
                  content:
                    log_level: INFO
                    replicas: 2
                  postgres_storage_requirements:
                    limits:
                      storage: 50Gi
                    requests:
                      storage: 8Gi
                  api:
                    log_level: INFO
                    replicas: 1
                  postgres_resource_requirements:
                    limits:
                      cpu: 1000m
                      memory: 8Gi
                    requests:
                      cpu: 500m
                      memory: 2Gi
                  redis:
                    log_level: INFO
                    replicas: 1
                  loadbalancer_protocol: http
                  resource_manager:
                    replicas: 1
                  worker:
                    replicas: 2
                  route_host: >-
                    {{ $.Values.name }}-hub.{{ `{{ (lookup "config.openshift.io/v1" "Ingress" "" "cluster").spec.domain }}` }}
                  storage_type: File
                  file_storage_access_mode: ReadWriteMany
                  file_storage_storage_class: ocs-storagecluster-cephfs
                  postgres_storage_class: ocs-storagecluster-ceph-rbd
                  redis_storage_class: ocs-storagecluster-cephfs
