---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: openshift-config
data:
  sync.yaml: |
    kind: LDAPSyncConfig
    apiVersion: v1
    url: '{{ $.Values.ldap_server }}/{{ $.Values.baseDN }}'
    insecure: false
    bindDN: {{ $.Values.bindDN | squote }}
    bindPassword:
      file: "/etc/secrets/bindPassword"
    ca: /etc/ldap-ca/ca.crt
    augmentedActiveDirectory:
      groupsQuery:
        baseDN: {{ $.Values.groupBaseDN | default $.Values.bindDN | squote }}
        scope: sub
        derefAliases: never
        pageSize: 0
      groupUIDAttribute: dn
      groupNameAttributes: [ cn ]
      groupMembershipAttributes: [ memberOf ]
      usersQuery:
        baseDN: {{ $.Values.usersBaseDN | default $.Values.bindDN | squote }}
        scope: sub
        derefAliases: never
        filter: (objectclass=person)
        pageSize: 0
      userUIDAttribute: dn
      userNameAttributes: [ {{ $.Values.preferredUsername | default "uid" }} ]
