---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: Active Directory LDAPS
    mappingMethod: add
    type: LDAP
    ldap:
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - {{ $.Values.preferredUsername | default "uid" }}
      bindDN: '{{ $.Values.bindDN }}'
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false
      url: '{{ $.Values.ldap_server }}/{{ $.Values.baseDN }}{{ if $.Values.preferredUsername }}?{{ $.Values.preferredUsername | default "uid" }}{{- end }}'
