---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $.Values.acm_policy_name }}
  namespace: {{ $.Values.policy_namespace | default "default" }}
spec:
  disabled: false
  remediationAction: {{ $.Values.remediation_action | default "inform" }}
  policy-templates:
  {{- if eq $.Values.migrate_openshift_dns true }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-dns-migration
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: DNS
                metadata:
                  name: default
                spec:
                  nodePlacement:
                    nodeSelector:
                      {{ $.Values.node.selector }}
                    tolerations:
                    {{- range $k, $v := $.Values.node.tolerations }}
                    - key: {{ $v.key }}
                      effect: {{ $v.effect }}
                      operator: {{ $v.operator }}
                      value: {{ squote $v.value }}
                    {{- end -}}
  {{- end }}
  {{- if eq $.Values.migrate_ingress_controller true }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ingress-controller-migration
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: IngressController
                metadata:
                  name: default
                  namespace: openshift-ingress-operator
                spec:
                  replicas: {{ $.Values.ingress_controller_replicas | default "3" | int }}
                  nodePlacement:
                    nodeSelector:
                      matchLabels:
                        {{ $.Values.node.selector }}
                    tolerations:
                    {{- range $k, $v := $.Values.node.tolerations }}
                    - key: {{ $v.key }}
                      effect: {{ $v.effect }}
                      operator: {{ $v.operator }}
                      value: {{ squote $v.value }}
                    {{- end -}}
  {{- end }}
  {{- if eq $.Values.migrate_image_registry true }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: internal-image-registry-migration
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: imageregistry.operator.openshift.io/v1
                kind: Config
                metadata:
                  name: cluster
                spec:
                  replicas: {{ $.Values.image_registry_replicas | default "3" | int }}
                  nodeSelector:
                    {{ $.Values.node.selector }}
                  tolerations:
                  {{- range $k, $v := $.Values.node.tolerations }}
                  - key: {{ $v.key }}
                    effect: {{ $v.effect }}
                    operator: {{ $v.operator }}
                    value: {{ squote $v.value }}
                  {{- end -}}
  {{- end }}
  {{- if eq $.Values.migrate_openshift_monitoring true }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-monitoring-migration
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: cluster-monitoring-config
                  namespace: openshift-monitoring
                data:
                  config.yaml: |+
                  {{- range $.Values.openshift_monitoring_stack }}
                    {{ . }}:
                      nodeSelector:
                        {{ $.Values.node.selector }}
                      tolerations:
                      {{- range $k, $v := $.Values.node.tolerations }}
                      - key: {{ $v.key }}
                        effect: {{ $v.effect }}
                        operator: {{ $v.operator }}
                        value: {{ squote $v.value }}
                      {{- end -}}
                  {{- end -}}
  {{- end -}}

