---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ $.Values.service_account_name }}
  namespace: {{ $.Values.central_namespace | default "stackrox" }}
