---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $.Values.acm_policy_set_name }}-placement
  namespace: {{ $.Values.policy_set_namespace | default "default" }}
placementRef:
  name: {{ $.Values.acm_policy_set_name }}-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: {{ $.Values.acm_policy_set_name }}
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet