---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: {{ $.Values.acm_policy_set_name }}-placement
  namespace: {{ $.Values.policy_set_namespace | default "default" }}
spec:
  clusterSelector:
    matchExpressions:
      - key: cluster.open-cluster-management.io/clusterset
        operator: In
        values:
        - default
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable