---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: {{ $.Values.acm_policy_name }}-placement
  namespace: {{ $.Values.policy_namespace | default "default"}}
spec:
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - "true"
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
