---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $.Values.acm_policy_name }}
  namespace: {{ $.Values.policy_namespace | default "default"}}
spec:
  disabled: false
  remediationAction: {{ $.Values.remediation_action | default "inform" }}
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ $.Values.all.default_namespace }}-namespace
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: {{ $.Values.all.default_namespace }}
                  annotations: 
                    openshift.io/description: ACM policy configuration namespace applied to all clusters managed my ACM
    {{- range .Values.all.cluster_names }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{.}}-{{ $.Values.all.default_namespace }}-namespace
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: {{.}}-{{ $.Values.all.default_namespace }}
                  annotations: 
                    openshift.io/description: ACM policy configuration namespace specified for cluster "{{.}}"
    {{- end }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ $.Values.all.default_namespace }}-gitops-sa-admin-rb
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: sa-ocp-gitops-argocd-app-ctrl
                  namespace: {{ $.Values.all.default_namespace }}
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
                subjects:
                - kind: ServiceAccount
                  name: openshift-gitops-argocd-application-controller
                  namespace: openshift-gitops
    {{- range .Values.all.cluster_names }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{.}}-{{ $.Values.all.default_namespace }}-gitops-sa-admin-rb
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: sa-ocp-gitops-argocd-app-ctrl
                  namespace: {{.}}-{{ $.Values.all.default_namespace }}
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
                subjects:
                - kind: ServiceAccount
                  name: openshift-gitops-argocd-application-controller
                  namespace: openshift-gitops
    {{- end -}}
