---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: init-bundle-secrets-placement
  namespace: stackrox
spec:
  clusterSelector:
    matchExpressions:
      - key: name
        operator: NotIn
        values:
          - local-cluster
  clusterConditions: []