---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: {{ $.Values.acm_policy_set_name }}-placement
  namespace: {{ $.Values.policy_set_namespace | default "default" }}
spec:
  clusterSelector:
    matchExpressions:
      - key: name
        operator: NotIn
        values:
          - local-cluster
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
      
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $.Values.acm_policy_set_name }}-placement
  namespace: {{ $.Values.policy_set_namespace | default "default" }}
placementRef:
  name: {{ $.Values.acm_policy_set_name }}-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: {{ $.Values.acm_policy_set_name }}
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet

---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: {{ $.Values.acm_policy_set_name }}
  namespace: {{ $.Values.policy_set_namespace | default "default" }}
spec:
  description: "Set of ACM policies applied to all cluster(s) that is NOT labeled 'local-cluster'"
  policies:
  {{- range .Values.govern.acm_policies }}
    - {{.}}
  {{- end -}}
