---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $.Values.acm_policy_name }}
  namespace: {{ $.Values.policy_namespace | default (printf "%+v-%+v" $.Values.cluster_name $.Values.default_namespace) }}
spec:
  disabled: false
  remediationAction: {{ $.Values.remediation_action | default "inform" }}
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ $.Values.acm_policy_name }}
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  annotations:
                    rbac.authorization.kubernetes.io/autoupdate: "false"
                  name: self-provisioners
                subjects: null
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: Project
                metadata:
                  name: cluster
                spec:
                  projectRequestMessage: Please email 'OCPAdmin@sandbox.example.redhat.com' requesting access to create an Openshift project.
