---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $.Values.acm_policy_name }}
  namespace: {{ $.Values.policy_namespace | default "default" }}
spec:
  disabled: false
  remediationAction: {{ $.Values.remediation_action | default "inform" }}
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ $.Values.acm_policy_name }}
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  labels:
                    operators.coreos.com/web-terminal.openshift-operators: ''
                  name: web-terminal
                  namespace: openshift-operators
                spec:
                  channel: fast
                  installPlanApproval: Automatic
                  name: web-terminal
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace