---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $.Values.cluster_name }}-secret-store
  namespace: {{ $.Values.policy_namespace | default (printf "%+v-%+v" $.Values.cluster_name $.Values.default_namespace) }}
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
  {{- range .Values.secretstore }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata: 
          name: {{ .name }}-secret-store
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: external-secrets.io/v1beta1
                kind: SecretStore
                metadata:
                  name: {{ .name }}
                  namespace: {{ .namespace }}
                spec:
                  provider:
                    vault:
                      server: >-
                        https://vault.{{ `{{hub (lookup "config.openshift.io/v1" "Ingress" "" "cluster").spec.domain hub}}` }}
                      path: "kubernetes"
                      version: "v2"
                      auth:
                        kubernetes:
                          mountPath: "kubernetes"
                          role: {{ quote .role }}
                          serviceAccountRef:
                            name: "default"
  {{- end }}
