---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $.Values.cluster_name }}-{{ $.Values.acm_policy_name }}
  namespace: {{ $.Values.policy_namespace | default (printf "%+v-%+v" $.Values.cluster_name $.Values.default_namespace) }}
spec:
  dependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      name: openshift-storage-namespace
      namespace: ""
      compliance: Compliant
  disabled: false
  remediationAction: {{ $.Values.remediation_action | default "inform" }}
  policy-templates:
      objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata: 
          name: {{ $.Values.cluster_name }}-{{ $.Values.acm_policy_name }}
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
          {{- range .Values.secretstore }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: external-secrets.io/v1beta1
                kind: SecretStore
                metadata:
                  name: {{ .name }}
                  namespace: {{ .namespace }}
                spec:
                  provider:
                    vault:
                      server: >-
                        https://vault.{{ `{{hub (lookup "config.openshift.io/v1" "Ingress" "" "cluster").spec.domain | protect hub}}` }}
                      path: "kubernetes"
#                      version: "v2"
                      auth:
                        kubernetes:
                          mountPath: "kubernetes"
                          role: {{ quote .role }}
          {{- end }}
