{{ range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  refreshInterval: {{ quote .refreshInterval }}
  secretStoreRef:
    name: {{ .secretStoreRefName }}
    kind: SecretStore
  target:
    name: {{ .name }}
  {{- if eq .type "generic" }}
  data:
    {{- range .secretData }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRefKey }}
        property: {{ .secretKey }}
    {{- end }}
  {{- else if eq .type "tls" }}
    template:
      type: kubernetes.io/tls
  data:
    {{- range .secretData }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRefKey }}
        property: {{ .secretKey }}
    {{- end }}
  {{- else }}
  dataFrom:
    {{- with (first .secretData) }}
    - extract:
        key: {{ .remoteRefKey }}
    {{- end }}
  {{- end }}
{{- end }}