---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: acs-central-url-placement
  namespace: rhacs-operator
spec:
  clusterSelector:
    matchExpressions:
      - key: name
        operator: NotIn
        values:
          - local-cluster
  clusterConditions: []