---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: acs-central-url
  namespace: stackrox
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acs-central-url
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                data:
                  fqdn: '{{hub (lookup "route.openshift.io/v1" "Route" "stackrox" "central").spec.host | base64enc | protect hub}}'
                  port: >-
                    {{hub range $index, $ports := (lookup "v1" "Service" "stackrox" "central").spec.ports hub}}
                      {{hub print $ports.port | base64enc | protect hub}}
                    {{hub end hub}}
                kind: Secret
                metadata:
                  name: acs-central-url
                  namespace: stackrox
                type: Opaque