---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $.Values.cluster_name }}-{{ $.Values.acm_policy_name }}
  namespace: {{ $.Values.policy_namespace | default (printf "%+v-%+v" $.Values.cluster_name $.Values.default_namespace) }}
spec:
  disabled: false
  remediationAction: {{ $.Values.remediation_action | default "inform" }}
  policy-templates:
  {{- range .Values.machines }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ .type }}-{{ .availability_zone }}-{{ $.Values.acm_policy_name }}
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: machine.openshift.io/v1beta1
                kind: MachineSet
                metadata:
                  labels:
                    #machine.openshift.io/cluster-api-cluster: {{ $.Values.cluster_id }}
                    machine.openshift.io/cluster-api-cluster: {{ '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}' }}
                  #name: {{ $.Values.cluster_id }}-{{ .type }}-{{ .availability_zone }}
                  name: {{ '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-{{ .type }}-{{ .availability_zone }}' }}
                  namespace: openshift-machine-api
                spec:
                  replicas: 1
                  selector:
                    matchLabels:
                      #machine.openshift.io/cluster-api-cluster: {{ $.Values.cluster_id }}
                      machine.openshift.io/cluster-api-cluster: {{ '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}' }}
                      machine.openshift.io/cluster-api-machineset: {{ $.Values.cluster_id }}-{{ .type }}-{{ .availability_zone }}
                  template:
                    metadata:
                      labels:
                        machine.openshift.io/cluster-api-cluster: {{ $.Values.cluster_id }}
                        {{ if eq .type "app" -}} 
                        machine.openshift.io/cluster-api-machine-role: worker 
                        {{- else -}} 
                        machine.openshift.io/cluster-api-machine-role: infra 
                        {{- end }}
                        machine.openshift.io/cluster-api-machine-type: worker
                        machine.openshift.io/cluster-api-machineset: {{ $.Values.cluster_id }}-{{ .type }}-{{ .availability_zone }}
                    spec:
                      lifecycleHooks: {}
                      metadata:
                      {{- if eq .type "app" }}
                        labels:
                          node-role.kubernetes.io/app: ""
                          node-role.kubernetes.io/worker: ""
                      {{- else if eq .type "odf" }}
                        labels:
                          node-role.kubernetes.io/odf: ""
                          node-role.kubernetes.io/infra: ""
                          node-role.kubernetes.io/worker: ""
                          cluster.ocs.openshift.io/openshift-storage: ""
                      taints:
                      - effect: NoSchedule
                        key: node.ocs.openshift.io/storage
                        value: "true"
                      {{- else if eq .type "infra" }}
                        labels:
                          node-role.kubernetes.io/infra: ""
                          node-role.kubernetes.io/worker: ""
                          node-role.kubernetes.io/cluster-infra: ""
                      taints:
                      - effect: NoSchedule
                        key: node-role.kubernetes.io/infra
                        value: "true"
                      - effect: NoExecute
                        key: node-role.kubernetes.io/infra
                        value: "true"
                      {{- end }}
                      providerSpec:
                        value:
                          ami:
                            id: {{ $.Values.ami_id }}
                          apiVersion: awsproviderconfig.openshift.io/v1beta1
                          blockDevices:
                          - ebs:
                            {{- if $.Values.enable_kms_encryption }}
                              encrypted: true
                              kmsKey:
                                arn: {{ $.Values.kms_Key_ARN }}
                            {{- end }}
                              volumeSize: {{ $.Values.storage_size | default "120" }}
                              volumeType: {{ $.Values.storage_type | default "gp2" }}
                          credentialsSecret:
                            name: aws-cloud-credentials
                          deviceIndex: 0
                          iamInstanceProfile:
                            id: {{ $.Values.cluster_id }}-worker-profile
                          {{ if eq .type "app" -}}
                          instanceType: {{ $.Values.app_instanceType | default "r5.xlarge" }}
                          {{- else if eq .type "odf" -}}
                          instanceType: {{ $.Values.odf_instanceType | default "m5.2xlarge" }}
                          {{- else if eq .type "infra" -}}
                          instanceType: {{ $.Values.infra_instanceType | default "m5.xlarge" }}
                          {{- end }}
                          kind: AWSMachineProviderConfig
                          metadata:
                            creationTimestamp: null
                          placement:
                            availabilityZone: {{ .availability_zone }}
                            region: {{ $.Values.region }}
                          securityGroups:
                          - filters:
                            - name: tag:Name
                              values:
                              - {{ $.Values.cluster_id }}-worker-sg
                          subnet:
                          {{- if $.Values.machineset_use_subnet_id }}
                            id: {{ .subnet_id }}
                          {{- else }}
                            filters:
                              - name: 'tag:Name'
                                values:
                                  - {{ $.Values.cluster_id }}-private-{{ .availability_zone }}
                          {{- end }}
                          tags:
                          - name: kubernetes.io/cluster/{{ $.Values.cluster_id }}
                            value: owned
                          - name: environment
                            value: {{ $.Values.env }}
                          - name: region
                            value: {{ $.Values.region }}
                          - name: availability_zone
                            value: {{.availability_zone }}
                          - name: machine_type
                            value: {{ .type }}
                          - name: machine_name
                            value: {{ $.Values.cluster_id }}-{{ .type }}-{{ .availability_zone }}
                          userDataSecret:
                            name: worker-user-data
  {{- end -}}
