---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: {{ $.Values.acm_policy_set_name }}-placement
  namespace: {{ $.Values.policy_set_namespace | default "default" }}
spec:
  clusterSelector:
    matchExpressions:
      - key: cluster.open-cluster-management.io/clusterset
        operator: In
        values:
        - default
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
      
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $.Values.acm_policy_set_name }}-placement
  namespace: {{ $.Values.policy_set_namespace | default "default" }}
placementRef:
  name: {{ $.Values.acm_policy_set_name }}-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: {{ $.Values.acm_policy_set_name }}
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet

---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: {{ $.Values.acm_policy_set_name }}
  namespace: {{ $.Values.policy_set_namespace | default "default" }}
spec:
  description: "Set of basline ACM policies applied to all cluster(s) managed by Openshift's ACM"
  policies:
  {{- range .Values.baseline.acm_policy }}
    - {{.}}
  {{- end -}}
