---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $.Values.cluster_name }}-{{ $.Values.acm_policy_name }}
  namespace: {{ $.Values.policy_namespace | default (printf "%+v-%+v" $.Values.cluster_name $.Values.default_namespace) }}
spec:
  disabled: false
  remediationAction: {{ $.Values.remediation_action | default "inform" }}
  policy-templates:
  {{- if $.Values.update_proxy_with_root_ca }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: root-ca-cert-config-map
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                data:
                  ca-bundle.crt: |
                    {{- .Files.Get .Values.tls.caPath | trim | nindent 20 }}
                kind: ConfigMap
                metadata:
                  name: {{ $.Values.ca_cert_configmap_name }}
                  namespace: openshift-config
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: update-proxy-config-with-root-ca
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: Proxy
                metadata:
                  name: cluster
                  spec:
                    trustedCA:
                      name: {{ $.Values.ca_cert_configmap_name }}
    {{- end }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: wildcard-cert-secret
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                data:
                  tls.crt: {{ .Files.Get .Values.tls.certPath | b64enc }}
                  tls.key: {{ .Files.Get .Values.tls.keyPath | b64enc }}
                kind: Secret
                metadata:
                  name: {{ $.Values.ingress_cert_secret_name }}
                  namespace: openshift-ingress
                type: kubernetes.io/tls
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: update-ingress-controller-config-with-new-cert
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: IngressController
                metadata:
                  name: default
                  namespace: openshift-ingress-operator
                spec:
                  defaultCertificate:
                    name: {{ $.Values.ingress_cert_secret_name }}
