apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
 name: console-banner
spec:
 # Banner Text:
 text: "{{ upper .Values.cluster_name }} OpenShift Container Platform {{ .Values.targetrevision }} "
 # Other options are BannerBottom, BannerTopBottom
 location: BannerTopBottom
 # Hexcode for white text color
 color: "{{ .Values.cluster_banner.textColor }}"
 # Hexcode for banner background color
 backgroundColor: "{{ .Values.cluster_banner.backgroundColor }}"