---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: {{ $.Values.cluster_name }}-{{ $.Values.acm_policy_name }}-placement
  namespace: {{ $.Values.policy_namespace | default (printf "%+v-%+v" $.Values.cluster_name $.Values.default_namespace) }}
spec:
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
        - {{ $.Values.cluster_name }}
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
      
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $.Values.cluster_name }}-{{ $.Values.acm_policy_name }}-placement
  namespace: {{ $.Values.policy_namespace | default (printf "%+v-%+v" $.Values.cluster_name $.Values.default_namespace) }}
placementRef:
  name: {{ $.Values.cluster_name }}-{{ $.Values.acm_policy_name }}-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: {{ $.Values.cluster_name }}-{{ $.Values.acm_policy_name }}
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet

---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: {{ $.Values.cluster_name }}-{{ $.Values.acm_policy_name }}
  namespace: {{ $.Values.policy_namespace | default (printf "%+v-%+v" $.Values.cluster_name $.Values.default_namespace) }}
spec:
  description: ACM policies specific to cluster "{{ $.Values.cluster_name }}"
  policies:
  {{- range .Values.cluster.acm_policy }}
    - {{ $.Values.cluster_name }}-{{.}}
  {{- end -}}
