---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $.Values.cluster_name }}-{{ $.Values.acm_policy_name }}
  namespace: {{ $.Values.policy_namespace | default (printf "%+v-%+v" $.Values.cluster_name $.Values.default_namespace) }}
spec:
  dependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      kind: Policy
      name: {{ $.Values.cluster_name }}-secret-store
      namespace: {{ $.Values.policy_namespace | default (printf "%+v-%+v" $.Values.cluster_name $.Values.default_namespace) }}
      compliance: Compliant
  disabled: false
  remediationAction: {{ $.Values.remediation_action | default "inform" }}
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ $.Values.cluster_name }}-{{ $.Values.acm_policy_name }}
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
          {{- range $es := .Values.externalSecrets }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                metadata:
                  name: {{ $es.name }}
                  namespace: {{ $es.namespace }}
                spec:
                  data:
                  {{- range .secretData }}
                    - remoteRef:
                        conversionStrategy: Default
                        decodingStrategy: None
                        key: {{ .remoteRefKey | default (printf "%+v/%+v" $es.namespace $es.name) }}
                        property: {{ .secretKey }}
                      secretKey: {{ .secretKey }}
                  {{- end }}
                  refreshInterval: {{ $es.refreshInterval | default "1m" }}
                  secretStoreRef:
                    kind: SecretStore
                    name: {{ $es.secretStoreRefName }}
                  target:
                    creationPolicy: Owner
                    deletionPolicy: Retain
                    name: {{ $es.name }}
                  {{- if eq $es.tlsTemplate true }}
                    template:
                      type: kubernetes.io/tls
                  {{- end }}
          {{- end }}
