---
acm_policy_name: machineset
env: Sandbox Demo
cluster_id: sandbox-lmnop

#
# remediation_action defaults to 'inform' but, can be set to 'enforce'
#
remediation_action: inform

#
# severity defaults to 'low' but, can be set to 'medium' or 'high'
#
severity: high

#
# specify this policy namespace by passing a string value to policy_namespace. policy_namespace value must already be created.
# If policy_namespace: is blank or doesn't exists, then namespace will be <cluster_name>-<default_namespace>
#
policy_namespace:
#
cluster_name: sandbox
default_namespace: acm-policy

machineset_use_subnet_id: false
region: us-east-2
machines:
  - type: app
    availability_zone: us-east-2a
    subnet_id: subnet-123
  - type: app
    availability_zone: us-east-2b
    subnet_id: subnet-456
  - type: app
    availability_zone: us-east-2c
    subnet_id: subnet-789
  - type: odf
    availability_zone: us-east-2a
    subnet_id: subnet-123
  - type: odf
    availability_zone: us-east-2b
    subnet_id: subnet-456
  - type: odf
    availability_zone: us-east-2c
    subnet_id: subnet-789
  - type: infra
    availability_zone: us-east-2a
    subnet_id: subnet-123
  - type: infra
    availability_zone: us-east-2b
    subnet_id: subnet-456
  - type: infra
    availability_zone: us-east-2c
    subnet_id: subnet-789

enable_kms_encryption: true
kms_Key_ARN: <AWS ARN KMS Key>
ami_id: 

storage_type: gp3
storage_size: 100
app_instanceType: r5.2xlarge
odf_instanceType: m5.4xlarge
infra_instanceType: m5.xlarge
