---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mgmt-{{ $.Values.svm }}
mountOptions: 
  - nfsvers=4.1
parameters:
  backendType: "ontap-nas"
  provisioningType: "thin"
  snapshots: "true"
storagePools:
  - provisioningType: thin
  - backendType: ontap-nas
  - snapshots: true
provisioner: csi.trident.netapp.io
allowVolumeExpansion: true
volumeBindingMode: Immediate