---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $.Values.acm_policy_name }}
  namespace: {{ $.Values.policy_namespace | default "default" }}
spec:
  dependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      name: compliance-operator-status
      namespace: ""
      compliance: Compliant
  disabled: false
  remediationAction: {{ $.Values.remediation_action | default "inform" }}
  policy-templates:
  {{- range $.Values.node }}
    {{- if eq .enable_scan_setting true }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
        {{- if .name }}
          name: {{ .role }}-{{ .name }}-scansetting
        {{- else }}
          name: {{ .role }}-scansetting
        {{- end }}
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: compliance.openshift.io/v1alpha1
                kind: ScanSetting
                metadata:
                {{- if .name }}
                  name: {{ .role }}-{{ .name }}
                {{- else }}
                  name: {{ .role }}
                {{- end }}
                  namespace: openshift-compliance
                strictNodeScan: true
                showNotApplicable: false
                {{- if eq $.Values.apply_auto_remediations true }}
                autoApplyRemediations: true
                autoUpdateRemediations: true
                {{- end }}
                schedule: 0 1 * * *
                rawResultStorage:
                  storageClassName: {{ $.Values.compliance_scan_storage_class_name | default "gp2" }}
                {{- if .selector }}
                  nodeSelector:
                    {{ .selector }}
                {{- end -}}
                {{- if .tolerations }}
                  tolerations:
                  {{- range $k, $v := .tolerations }}
                  - key: {{ $v.key }}
                    effect: {{ $v.effect }}
                    operator: {{ $v.operator }}
                    {{- if $v.value }}
                    value: {{ squote $v.value }}
                    {{- end -}}
                  {{- end -}}
                {{- end }}
                  pvAccessModes:
                    - ReadWriteOnce
                  rotation: 3
                  size: 1Gi
                roles:
                - {{ .role }}
              {{- if .tolerations }}
                scanTolerations:
                {{- range $k, $v := .tolerations }}
                - key: {{ $v.key }}
                  effect: {{ $v.effect }}
                  operator: {{ $v.operator }}
                  {{- if $v.value }}
                  value: {{ squote $v.value }}
                  {{- end -}}
                {{- end -}}
              {{- end }}
    {{- end }}
  {{- end }}
  {{- range $.Values.node }}
    {{- if eq .enable_scan_setting true }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
        {{- if .name }}
          name: {{ .role }}-{{ .name }}-scansettingbindings
        {{- else }}
          name: {{ .role }}-scansettingbindings
        {{- end }}
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: ScanSettingBinding
                apiVersion: compliance.openshift.io/v1alpha1
                metadata:
                {{- if .name }}
                  name: {{ .role }}-{{ .name }}
                {{- else }}
                  name: {{ .role }}
                {{- end }}
                  namespace: openshift-compliance
                profiles:
                {{- range $k, $v := .scan_profile }}
                  - apiGroup: compliance.openshift.io/v1alpha1
                    kind: Profile
                    name: {{ $v.name }}
                {{- end }}
                settingsRef:
                  apiGroup: compliance.openshift.io/v1alpha1
                  kind: ScanSetting
                {{- if .name }}
                  name: {{ .role }}-{{ .name }}
                {{- else }}
                  name: {{ .role }}
                {{- end }}
    {{- end }}
  {{- end }}
